name: integration-opensuse-leap

on:
  push:
    branches:
      - openSUSE/release/3006.0
  pull_request:
    branches:
      - openSUSE/release/3006.0
  workflow_dispatch:

jobs:
  integration-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Salt
        uses: actions/checkout@v2
        with:
          path: salt
      - name: Checkout Salt Toaster
        uses: actions/checkout@v2
        with:
          repository: openSUSE/salt-toaster
          path: salt-toaster
          ref: 3006
      - name: Integration tests
        env:
          # The "ghcr.io/opensuse/salt-toaster-leap15.4-devel" package is currently private.
          # Uncomment DOCKER_IMAGE once the image is public.
          #
          # https://github.com/orgs/openSUSE/packages?repo_name=salt-toaster
          #
          # DOCKER_IMAGE: "ghcr.io/opensuse/salt-toaster-leap15.4-devel"
          DISTRO: "leap15.4"
          FLAVOR: "devel"
          SALT_REPO: "${{ github.workspace }}/salt"
          PYTEST_FLAGS: "--run-slow --core-tests --run-destructive --ssh-tests --run-expensive -vvvv"
        working-directory: ./salt-toaster
        run: make saltstack.integration
