name: integration-opensuse-leap

on:
  push:
    branches:
      - openSUSE/release/3004
  pull_request:
    branches:
      - openSUSE/release/3004
  workflow_dispatch:

jobs:
  integration-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Salt
        uses: actions/checkout@v2
        with:
          path: salt
      - name: Checkout Salt Toaster
        uses: actions/checkout@v2
        with:
          repository: openSUSE/salt-toaster
          path: salt-toaster
          ref: 3004
      - name: Integration tests
        env:
          DOCKER_IMAGE: "ghcr.io/opensuse/salt-toaster-leap15.3-devel"
          DISTRO: "leap15.3"
          FLAVOR: "devel"
          SALT_REPO: "${{ github.workspace }}/salt"
        working-directory: ./salt-toaster
        run: make saltstack.integration
