name: unit-opensuse-leap-15-1
on: pull_request
jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Salt
        uses: actions/checkout@v2
        with:
          path: salt
      - name: Checkout Salt Toaster
        uses: actions/checkout@v2
        with:
          repository: openSUSE/salt-toaster
          path: salt-toaster
      - name: Unit tests
        run: cd $GITHUB_WORKSPACE/salt-toaster && make saltstack.unit VERSION=opensuse151 FLAVOR=devel SALT_REPO=$GITHUB_WORKSPACE/salt
